library(dplyr)
class <- c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric")
data <- read.csv("household_power_consumption.txt", sep = ";", skip = 60000, nrows = 10000, header=FALSE, na.strings = "?", colClasses = class)
datadaytime <- mutate(data, daytime = gsub(" ART", "", strptime(paste(data[,1],data[,2], sep=":"), "%d/%m/%Y:%H:%M:%S")))
subdata <- subset(datadaytime, format(as.Date(datadaytime[, 10]), "%Y-%m-%d") == "2007-02-01" | format(as.Date(datadaytime[, 10]), "%Y-%m-%d") == "2007-02-02")
subdata$posix <- as.POSIXlt(subdata$daytime)
Sys.setlocale("LC_TIME", "English")
png("plot2.png", width = 480, height = 480, units = "px")
plot(subdata$posix, subdata$V3, type ="l", ylab = "Global Active Power (Kilowatts)", xlab = "")
dev.off()
Sys.setlocale("LC_TIME", "Spanish_Chile.1252")
