library(dplyr)
class <- c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric")
data <- read.csv("household_power_consumption.txt", sep = ";", skip = 60000, nrows = 10000, header=FALSE, na.strings = "?", colClasses = class)
datadaytime <- mutate(data, daytime = gsub(" ART", "", strptime(paste(data[,1],data[,2], sep=":"), "%d/%m/%Y:%H:%M:%S")))
subdata <- subset(datadaytime, format(as.Date(datadaytime[, 10]), "%Y-%m-%d") == "2007-02-01" | format(as.Date(datadaytime[, 10]), "%Y-%m-%d") == "2007-02-02")
subdata$posix <- as.POSIXlt(subdata$daytime)
Sys.setlocale("LC_TIME", "English")
png("plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
with(subdata, {
  plot(subdata$posix, subdata$V3, type ="l", ylab = "Global Active Power", xlab = "")
  plot(subdata$posix, subdata$V5, type ="l", ylab = "Voltage", xlab = "datetime")
  with(subdata, plot(subdata$posix, subdata$V7, type ="n", ylab = "Energy sub metering", xlab = ""))
  points(subdata$posix, subdata$V8, type ="l", col ="red")
  points(subdata$posix, subdata$V9, type ="l", col ="blue")
  points(subdata$posix, subdata$V7, type ="l", col = "black")
  legend("topright", inset = 0.02, lty = 1, xjust = 1, box.lty = 0, cex = 0.8, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(subdata$posix, subdata$V4, type ="l", ylab = "Global_reactive_power", xlab = "datetime")
})
dev.off()
Sys.setlocale("LC_TIME", "Spanish_Chile.1252")

